name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

  runs-on: ubuntu-latest
    -name: install make
      run: sudo apt istall cmake
    -name: build
      run: make
    
